### ISSUE TITLE
goog:chromeOptions throwing fatal error?

### ISSUE THREAD

**Issue by validaide-mark-bijl** [robertfausk/behat-panther-extension#16]
Dear Robert,

First of all thank you for making this package! We are trying out this package as a replacement for our Selenium approach. Everything appeared to work fine as a drop-in replacement, until we attempted to configure the Chrome download directory to test for downloads.

When we configure the 'goog:chromeOptions' as described:

```yml
...
        javascript_chrome:
          panther:
            options:
              browser: 'chrome'
              webServerDir: '%paths.base%/public'
            manager_options:
              connection_timeout_in_ms: 5000
              request_timeout_in_ms: 120000
              chromedriver_arguments:
                - --window-size=1280,1600
                - --log-path=var/build/chromedriver.log
#                - --verbose
              capabilities:
                goog:chromeOptions:
                  prefs:
                    download.default_directory: 'var/build'
...
```
we get the following error:
```bash
Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Call to a member function addArguments() on array in vendor/symfony/panther/src/ProcessManager/ChromeManager.php:68
```

Now either we're overlooking something in our YML file, or could it be that something is amiss in the processing of the 'goog:chromeOptions' part?

It seems here:
```php
vendor/symfony/panther/src/ProcessManager/ChromeManager.php

...
 if ($this->arguments) {
            $chromeOptions = $capabilities->getCapability(ChromeOptions::CAPABILITY);
            if (null === $chromeOptions) {
                $chromeOptions = new ChromeOptions();
                $capabilities->setCapability(ChromeOptions::CAPABILITY, $chromeOptions);
            }
            $chromeOptions->addArguments($this->arguments);

            if (isset($_SERVER['PANTHER_CHROME_BINARY'])) {
                $chromeOptions->setBinary($_SERVER['PANTHER_CHROME_BINARY']);
            }
        }
...
```

That this statement `$chromeOptions = $capabilities->getCapability(ChromeOptions::CAPABILITY);` returns an array, and not a ChromeOptions object..?

Are we doing something wrong on our end, and if so, could you help us point out the mistake, or... is something not adding up?

Your help much appreciated!
Thanks,
Mark
