### ISSUE TITLE
Create \Facebook\WebDriver\Remote\DesiredCapabilities from manager_options.capabilities, if provided

### ISSUE THREAD

**Issue by dkarlovi** [robertfausk/behat-panther-extension#17]
With latest Panther, it's possible to do this:

```yaml
default:
    extensions:
        Robertfausk\Behat\PantherExtension: ~
        Behat\MinkExtension:
            base_url: http://web/
            sessions:
                panther:
                    panther:
                        options:
                            browser: selenium
                        manager_options:
                            host: http://chrome:4444/wd/hub
```

If `manager_options.capabilities` are given here, they will be injected into the Selenium manager as is (PHP array), but should be converted into an instance of `\Facebook\WebDriver\Remote\DesiredCapabilities` which is expected:

https://github.com/symfony/panther/blob/b7e0f834c9046918972edb3dde2ecc4a20f6155e/src/ProcessManager/SeleniumManager.php#L32

Basically, this

```yaml
# as before
                        manager_options:
                            host: http://chrome:4444/wd/hub
                            capabilities:
                                acceptSslCerts: true
```

should work.
