### ISSUE TITLE
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found

### ISSUE THREAD

**Issue by guilhemVB** [robertfausk/behat-panther-extension#4]
Hi,

I've created a new symfony 4.4 project, and when I try to run vendor/bin/behat I have a PHP error.

```
$ vendor/bin/behat           

PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /home/guilhem/projets/test_panther/vendor/symfony/framework-bundle/Test/KernelTestCase.php on line 24

In KernelTestCase.php line 24:
                                                                          
  Attempted to load class "TestCase" from namespace "PHPUnit\Framework".  
  Did you forget a "use" statement for another namespace?                
``` 

My behat configuration : 
```
default:
    suites:
        default:
            contexts:
                - App\Tests\Behat\DemoContext

    extensions:
        Robertfausk\Behat\PantherExtension: ~
        FriendsOfBehat\SymfonyExtension: null
        Behat\MinkExtension:
            sessions:
                default:
                   panther: ~
```

Do you have any idea ?
Maybe I did a wrong configuration.

Thanks a lot !
